### ISSUE TITLE
Incorrect body parameters.

### ISSUE THREAD

**Issue by IvanGoncharov** [sendgrid/sendgrid-oai#9]
In one of latest updates you added following:

``` yaml
      parameters:
        - in: body
          name: body
          schema:
            type: 'null'
```

It looks like you tried to specify that body should be empty, but instead, it means you expect  JSON `null` as payload.
If you want to specify that body param should be empty just omit body param.
